export const SESSIONS = [
  {
    id: 's1',
    date: '2026-09-04',
    subject: 'Retrato clássico',
    imageId: '1506794778202-cad84cf45f1d',
    status: 'done',
    psnr: 32.4,
    ssim: 0.87,
  },
  {
    id: 's2',
    date: '2026-09-03',
    subject: 'Rua histórica',
    imageId: '1477959858617-67f85cf4f1df',
    status: 'done',
    psnr: 29.1,
    ssim: 0.82,
  },
  {
    id: 's3',
    date: '2026-09-02',
    subject: 'Paisagem rural',
    imageId: '1500534314209-a25ddb2bd429',
    status: 'done',
    psnr: 33.8,
    ssim: 0.91,
  },
  {
    id: 's4',
    date: '2026-09-01',
    subject: 'Arquitetura',
    imageId: '1487958449943-2429e8be8625',
    status: 'failed',
  },
];

export const CHART_DATA = [
  { day: 'Seg', psnr: 29.2, ssim: 0.81 },
  { day: 'Ter', psnr: 30.5, ssim: 0.83 },
  { day: 'Qua', psnr: 31.1, ssim: 0.85 },
  { day: 'Qui', psnr: 32.4, ssim: 0.87 },
  { day: 'Sex', psnr: 31.8, ssim: 0.86 },
  { day: 'Sáb', psnr: 33.2, ssim: 0.89 },
  { day: 'Dom', psnr: 32.9, ssim: 0.88 },
];

export const ADMIN_USERS = [
  {
    id: 1,
    name: 'Ana Souza',
    email: 'ana@colorize.ai',
    role: 'user',
    status: 'active',
    count: 34,
  },
  {
    id: 2,
    name: 'Bruno Lima',
    email: 'admin@colorize.ai',
    role: 'admin',
    status: 'active',
    count: 12,
  },
  {
    id: 3,
    name: 'Carla Mendes',
    email: 'carla@colorize.ai',
    role: 'user',
    status: 'active',
    count: 67,
  },
  {
    id: 4,
    name: 'Diego Ferreira',
    email: 'diego@colorize.ai',
    role: 'user',
    status: 'inactive',
    count: 5,
  },
  {
    id: 5,
    name: 'Elisa Ramos',
    email: 'elisa@colorize.ai',
    role: 'user',
    status: 'active',
    count: 102,
  },
  {
    id: 6,
    name: 'Felipe Costa',
    email: 'felipe@colorize.ai',
    role: 'user',
    status: 'active',
    count: 28,
  },
  {
    id: 7,
    name: 'Gabriela Nunes',
    email: 'gabriela@colorize.ai',
    role: 'admin',
    status: 'active',
    count: 9,
  },
  {
    id: 8,
    name: 'Henrique Pires',
    email: 'henrique@colorize.ai',
    role: 'user',
    status: 'inactive',
    count: 0,
  },
];

export const MONITORING_LOG = [
  {
    id: 'c001',
    user: 'Elisa Ramos',
    time: '14:32:05',
    duration: '2.8s',
    status: 'done',
    psnr: 33.1,
    ssim: 0.89,
  },
  {
    id: 'c002',
    user: 'Carla Mendes',
    time: '14:28:41',
    duration: '3.4s',
    status: 'done',
    psnr: 30.2,
    ssim: 0.84,
  },
  {
    id: 'c003',
    user: 'Ana Souza',
    time: '14:15:22',
    duration: '2.9s',
    status: 'done',
    psnr: 31.7,
    ssim: 0.86,
  },
  {
    id: 'c004',
    user: 'Felipe Costa',
    time: '13:58:10',
    duration: '–',
    status: 'failed',
    psnr: null,
    ssim: null,
  },
  {
    id: 'c005',
    user: 'Bruno Lima',
    time: '13:45:33',
    duration: '4.1s',
    status: 'done',
    psnr: 28.9,
    ssim: 0.80,
  },
  {
    id: 'c006',
    user: 'Gabriela Nunes',
    time: '13:12:07',
    duration: '3.0s',
    status: 'done',
    psnr: 32.5,
    ssim: 0.87,
  },
  {
    id: 'c007',
    user: 'Ana Souza',
    time: '12:55:18',
    duration: '3.1s',
    status: 'done',
    psnr: 29.7,
    ssim: 0.83,
  },
];